version: 2.0

phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/mservice.jar
  discard-paths: yes
